version: '3.8'

services:
  db:
    image: mysql:8.0.35-debian
    # restart: always
    container_name: db
    command: 
      - --lower_case_table_names=1
    env_file:
      - .env.dev
    environment:
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d

  backend:
    depends_on:
      - db
    # restart: always
    container_name: backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env.dev
    environment:
      TZ: Asia/Seoul
    ports:
      - "8000:8000"
    volumes:
      - ./acbo:/app/acbo

  
  frontend:
    image: nginx:1.24-bullseye
    # restart: always
    depends_on:
      - backend
    container_name: frontend
    environment:
      TZ: Asia/Seoul
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html

